### ISSUE TITLE
How do I restart Seq ?

### ISSUE THREAD

**Issue by CADbloke** [continuousit/seq-releases#264]
Debugging stuff in AutoCAD often involves killing `acad.exe` which leaves lots of other processes in a weird state, including Seq. is there a proper way to restart it without a reboot? I tried killing the Seq process and then running `run.bat` but that broke-pretty much everything. 

Crash stack ...

```
C:\Program Files\Seq>.\seq.exe run
────────────────────────────────────────
 │║█Seq ── © 2014 Continuous IT Pty Ltd
────────────────────────────────────────

Running as server; press Ctrl+C to exit.

2015-05-12 08:34:16 [Information] Seq "1.6.12.0" 64-bit running on .NET "4.0.30319.34209" and OS "Mi
crosoft Windows NT 6.1.7601 Service Pack 1" 64-bit
2015-05-12 08:34:24 [Information] Seq listening on http://localhost:5341/
2015-05-12 08:34:24 [Information] Opening document store "C:\ProgramData\Seq\Documents\default.quince"
2015-05-12 08:34:44 [Error] Uncaught exception from worker "Start app runner" (9be6371e-bc0b-45cb-aa
3c-e3453331e4a0)
Autofac.Core.DependencyResolutionException: An exception was thrown while executing a resolve operat
ion. See the InnerException for details. ---> Cannot access file, the file is locked or in use (See
inner exception for details.) ---> Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cann
ot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Instance.Init(InitGrbit grbit)
   at Quince.QuinceDB..ctor(String path, String instanceName)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c
, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnume
rable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parame
ters)
   at Seq.Server.SeqServerModule.<Load>b__5(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c
, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext cont
ext, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   at Autofac.Features.LazyDependencies.LazyRegistrationSource.<>c__DisplayClass5`1.<>c__DisplayClas
s7.<CreateLazyRegistration>b__4()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Seq.Server.ServiceProcess.ServerService.<Start>b__1(CancellationToken cancel)
   at Seq.Workers.WorkerPool.<>c__DisplayClass5.<Run>b__4()
2015-05-12 08:35:17 [Information] Opening document store "C:\ProgramData\Seq\Documents\default.quinc
e"
2015-05-12 08:35:37 [Error] Exception from task "Retention Policy"
Autofac.Core.DependencyResolutionException: An exception was thrown while executing a resolve operat
ion. See the InnerException for details. ---> Cannot access file, the file is locked or in use (See
inner exception for details.) ---> Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cann
ot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Instance.Init(InitGrbit grbit)
   at Quince.QuinceDB..ctor(String path, String instanceName)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c
, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnume
rable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parame
ters)
   at Seq.Server.SeqServerModule.<Load>b__4(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c
, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext cont
ext, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext cont
ext, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   at Seq.Server.Util.Autofac.UowRegistrationSource.<>c__DisplayClass2.<>c__DisplayClass4.<Registrat
ionsFor>b__1(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   at lambda_method(Closure )
   at Seq.Server.Tasks.TaskRunTimer.Execute(CancellationToken cancel)
   at Seq.Server.Tasks.TaskRunTimer.<OnTimer>b__2(CancellationToken cancel)
2015-05-12 08:36:37 [Information] Opening document store "C:\ProgramData\Seq\Documents\default.quinc
e"
2015-05-12 08:36:57 [Error] Exception from task "Retention Policy"
Autofac.Core.DependencyResolutionException: An exception was thrown while executing a resolve operat
ion. See the InnerException for details. ---> Cannot access file, the file is locked or in use (See
inner exception for details.) ---> Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cann
ot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Instance.Init(InitGrbit grbit)
   at Quince.QuinceDB..ctor(String path, String instanceName)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c
, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnume
rable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parame
ters)
   at Seq.Server.SeqServerModule.<Load>b__4(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c
, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext cont
ext, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext cont
ext, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   at Seq.Server.Util.Autofac.UowRegistrationSource.<>c__DisplayClass2.<>c__DisplayClass4.<Registrat
ionsFor>b__1(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context,
 IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOpera
tionScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerab
le`1 parameters)
   at lambda_method(Closure )
   at Seq.Server.Tasks.TaskRunTimer.Execute(CancellationToken cancel)
   at Seq.Server.Tasks.TaskRunTimer.<OnTimer>b__2(CancellationToken cancel)
2015-05-12 08:37:57 [Information] Opening document store "C:\ProgramData\Seq\Documents\default.quinc
e"
```

**Comment by nblumhardt** [comment]
Hi Ewen,

Seq runs as a Windows Service, so you should be able to restart it cleanly by clicking "Restart" in the Windows Services control panel applet.

Let me know if you hit any issues!

Regards,
Nick

**Comment by CADbloke** [comment]
Thanks Nick, I didn't see it there when I crashed it ... probably because I crashed it.
