### ISSUE TITLE
Cannot log to NLog SeqTarget when AccurateUTC enabled

### ISSUE THREAD

**Issue by wcoenen** [continuousit/seq-releases#276]
I followed the instructions for [Writing Events From NLog](https://getseq.atlassian.net/wiki/display/SEQ10/Writing+events+from+NLog), but I added `<time type='AccurateUTC' />` as a child of the root `nlog` element in nlog.config.

In this configuration, events will no longer be properly logged in seq. Under a debugger, I see a  `System.ArgumentException` occurring with this message

> The UTC Offset for Utc DateTime instances must be 0.
> Parameter name: offset

and this stacktrace:

<pre>
   at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
   at Seq.Client.NLog.LogEventInfoFormatter.ToJson(LogEventInfo loggingEvent, StringWriter payload, IList`1 properties) in c:\TeamCity\buildAgent\work\98a5da83bb08b935\src\Seq.Client.NLog\Client\NLog\LogEventInfoFormatter.cs:line 82
   at Seq.Client.NLog.LogEventInfoFormatter.ToJson(IEnumerable`1 events, StringWriter payload, IList`1 properties) in c:\TeamCity\buildAgent\work\98a5da83bb08b935\src\Seq.Client.NLog\Client\NLog\LogEventInfoFormatter.cs:line 69
   at Seq.Client.NLog.SeqTarget.PostBatch(IEnumerable`1 events) in c:\TeamCity\buildAgent\work\98a5da83bb08b935\src\Seq.Client.NLog\Client\NLog\SeqTarget.cs:line 90
   at Seq.Client.NLog.SeqTarget.Write(LogEventInfo logEvent) in c:\TeamCity\buildAgent\work\98a5da83bb08b935\src\Seq.Client.NLog\Client\NLog\SeqTarget.cs:line 80
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
</pre>

**Comment by nblumhardt** [comment]
Thanks for the report. The linked commit should have this sorted, a new package version will be up soon. Cheers!
