### ISSUE TITLE
Seq using high memory, poor performance

### ISSUE THREAD

**Issue by bendetat** [continuousit/seq-releases#347]
Hi, our Seq instance (2.3.3, single-user license) was non-responsive for ~ 2 days (over the weekend). 

The extents are somewhat large for a server this size (~32 GB, with 30 GB split between the two most recent weeks + sundry) and grow quickly, we've got some aggressive retention policies to keep disk space usage sane and there is 130+ GB free on the data drive  so I don't think disk space is the issue in this case.

Memory utilisation was floating around 98% with 5 GB (out of 8 GB) allocated to the Seq instance alone. This looks like a likely cause for the performance symptom, but not the root cause.

Restarting the server seems to have temporarily fixed the issue - Seq is responsive however memory usage has increased from ~2200 MB to ~3400 MB in 40 minutes. ~~I'll update if it dies again~~ It's stabilised at 4 GB. I imagine restarting the Seq instance alone would also have worked (other services were sluggy but usable), but the server was restarted before I could confirm that.

The following was in the tail internal log. `EsentVersionStoreOutOfMemoryException` looks interesting.

```
2015-10-26 00:31:30.010 +10:00 [Information] Uptime 7.21:23:35.0662350; Working set 2129068032 bytes; Thread pool ThreadPoolMetrics { AvailableUser: 32762, AvailableIocp: 976 }; Cache CacheMetrics { DaysRecorded: 32.625, DaysCached: 4.625, EventsCached: 5855622, FirstSegmentDateUtc: 09/23/2015 00:00:00, LastSegmentDateUtc: 10/25/2015 12:00:00 }
2015-10-26 02:15:50.163 +10:00 [Information] Uptime 7.23:07:55.2035191; Working set 2113437696 bytes; Thread pool ThreadPoolMetrics { AvailableUser: 32762, AvailableIocp: 979 }; Cache CacheMetrics { DaysRecorded: 32.75, DaysCached: 4.75, EventsCached: 5860133, FirstSegmentDateUtc: 09/23/2015 00:00:00, LastSegmentDateUtc: 10/25/2015 15:00:00 }
2015-10-26 03:42:46.439 +10:00 [Information] Uptime 8.00:34:51.4637724; Working set 2136555520 bytes; Thread pool ThreadPoolMetrics { AvailableUser: 32760, AvailableIocp: 983 }; Cache CacheMetrics { DaysRecorded: 32.75, DaysCached: 4.75, EventsCached: 5861467, FirstSegmentDateUtc: 09/23/2015 00:00:00, LastSegmentDateUtc: 10/25/2015 15:00:00 }
2015-10-26 05:48:27.063 +10:00 [Information] Uptime 8.02:40:32.1192372; Working set 2016247808 bytes; Thread pool ThreadPoolMetrics { AvailableUser: 32762, AvailableIocp: 984 }; Cache CacheMetrics { DaysRecorded: 32.875, DaysCached: 4.875, EventsCached: 5877704, FirstSegmentDateUtc: 09/23/2015 00:00:00, LastSegmentDateUtc: 10/25/2015 18:00:00 }
2015-10-26 07:12:48.104 +10:00 [Information] Uptime 8.04:04:53.0978993; Working set 1932050432 bytes; Thread pool ThreadPoolMetrics { AvailableUser: 32762, AvailableIocp: 983 }; Cache CacheMetrics { DaysRecorded: 32.875, DaysCached: 4.875, EventsCached: 5886278, FirstSegmentDateUtc: 09/23/2015 00:00:00, LastSegmentDateUtc: 10/25/2015 18:00:00 }
2015-10-26 08:45:08.541 +10:00 [Information] Uptime 8.05:37:13.5346120; Working set 1370976256 bytes; Thread pool ThreadPoolMetrics { AvailableUser: 32760, AvailableIocp: 983 }; Cache CacheMetrics { DaysRecorded: 33, DaysCached: 5, EventsCached: 5886299, FirstSegmentDateUtc: 09/23/2015 00:00:00, LastSegmentDateUtc: 10/25/2015 21:00:00 }
2015-10-26 08:46:57.287 +10:00 [Error] Error serving "http://REDACTED:600/api/events/raw" (token: "62e3e1ab0a3b4b81bc571c09aad6156e")
Microsoft.Isam.Esent.Interop.EsentVersionStoreOutOfMemoryException: Version store out of memory (cleanup already attempted)
   at Microsoft.Isam.Esent.Interop.Update.Save(Byte[] bookmark, Int32 bookmarkSize, Int32& actualBookmarkSize)
   at Seq.Storage.Isam.EventStoreExtent.Add(StorageEvent[] evts)
   at Seq.Storage.Events.EventStore.Add(StorageEventCreationData[] eventsCreationData)
   at Seq.Server.Web.Api.Events.RawEventsModule.CreateEventsFromRaw()
   at Seq.Server.Web.Api.Events.RawEventsModule.<.ctor>b__0(Object _)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
2015-10-26 08:46:57.287 +10:00 [Error] Error serving "http://REDACTED:600/api/events/raw" (token: "1c08d6d2c33943b781d2fea4f7753085")

... Same exception repeated ...
```

Cheers
Ben

**Comment by nblumhardt** [comment]
Hi Ben,

Thanks for the detailed report, much appreciated.

I think this is probably a duplicate of #341, which is fixed in the [2.4.1-pre](https://getseq.net/Download) build.

The 2.4 release is ready to go but for the report of a possible intermittent crash that we're waiting for reproduction of to determine if it's related to the new online compaction changes. If it doesn't repro in the next few days I think we'll be all clear to ship the 2.4 final.

I'll leave this open until we've got confirmation that your server is healthy and happy (though it does sound like a few more GB of RAM would be a worthwhile investment if you can find them :-))

Cheers,
Nick

**Comment by nblumhardt** [comment]
Hi Ben,

2.4 is out now, please let me know when you have a chance if you're still having any issues.

Cheers!
Nick

**Comment by bendetat** [comment]
Thanks Nick. I'm not with that client any more (as of Friday) but they didn't have any issues with a couple of days on 2.4.1. They have instructions to upgrade to 2.4.2. I'll check out the situation if I'm back there.

I'll close this issue. Thanks for your help ;-)

Ben
