### ISSUE TITLE
Logging Double.MinValue fails

### ISSUE THREAD

**Issue by nickfr** [continuousit/seq-releases#358]
The following line logs to file fine but fails on logging to seq

log1.Information("Min {min}", Double.MinValue);

Error appears to be from Seq rather than the sink:

2016-01-10T08:39:04 Exception while emitting periodic batch from Serilog.Sinks.Seq.SeqSink: System.AggregateException: One or more errors occurred. ---> Serilog.Debugging.LoggingFailedException: Received failed result InternalServerError when posting events to Seq
   at Serilog.Sinks.Seq.SeqSink.<EmitBatchAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
---> (Inner Exception #0) Serilog.Debugging.LoggingFailedException: Received failed result InternalServerError when posting events to Seq
   at Serilog.Sinks.Seq.SeqSink.<EmitBatchAsync>d__12.MoveNext()<---

**Comment by nblumhardt** [comment]
Thanks for the report Nick. I think this may be http://www.hanselman.com/blog/WhyYouCantDoubleParseDoubleMaxValueToStringOrSystemOverloadExceptionsWhenUsingDoubleParse.aspx - `MaxValue` causes trouble as well.

**Comment by nickfr** [comment]
thanks for tackling this - one question, after receiving this error the sink then stopping logging any subsequent messages. Is this something that can also be changed, or is it a defence - server broken, so don't bother sending more...

**Comment by nblumhardt** [comment]
Hi Nick - if you're using the "durable" shipping mode then logging will stop until the problem is resolved. Otherwise (without a durable filename specified) logging will eventually resume after a process of retries. This should take about 10 minutes, but that assumes there's no subsequent occurrences of the same problem.

Does this match your experience?

**Comment by chosenbreed37** [comment]
@nblumhardt This seems to match my experience (closer to 15 minutes).Is this still an issue? Is there a way to handle this in a way that keeps the logging going?

**Comment by nblumhardt** [comment]
@chosenbreed37 the `Double.MinValue` issue shouldn't be present anymore. The 3.0 version of Serilog.Sinks.Seq should also detect and recover from invalid payload issues without the retry process, so long as the server has returned a 4xx code (IIRC :-))

Have you checked out _Settings_ > _Diagnostics_ > _Ingestion log_ on the Seq server? Usually some clues in there - feel free to ping support@getseq.net with what you find, if you need a hand to sort it out :+1:
